version: '0.1'

services:
  springboot-app:
    image: sampledata
    build:
      context: .
      dockerfile: Dockerfile
    container_name: volumeconcept
    depends_on:
      - mysql
    ports:
      - "8080:8081"
    networks:
      - firstnetwork-project
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sampledatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Kundu123@123

  mysql:
    image: mysql:latest
    container_name: revshop_db
    ports:
      - "3305:3306"
    networks:
      - firstnetwork-project
    environment:
      MYSQL_ROOT_PASSWORD: Kundu123@123
      MYSQL_DATABASE: sampledatabase
    volumes:
      - mysql_data:/var/lib/mysql # Data persistence

networks:
  firstnetwork-project:

volumes:
  mysql_data: # Named volume for MySQL data
